### PR TITLE
Fix to manifest generation for certain games, also allows dependencies to be read/packed at any position?

### PR DESCRIPTION
**Pull request by 190nm**
#22 Admittedly I've never written go before in my life but I tried my hand at fixing this based off the info given, _seems_ to work, but I've only tested it on samples from Pikmin 4 (UE 4.26.2)

### CODE REVIEW

**Comment by Real-n3tron** [comment]
Getting fatal error while creating manifest file for efootball 23

**Comment by 190nm** [comment]
> Getting fatal error while creating manifest file for efootball 23

can you provide a sample? I can try to take a look

**Comment by Real-n3tron** [comment]
[]()https://drive.google.com/file/d/1Hd6i_mvkiqe4Ov1S4wbBAIr2YuDz6Y3x/view?usp=drivesdk


In this link u will find a ucas ,utoc ,pak file from Efootball 23.

**Comment by CadiLillian** [comment]
> Getting fatal error while creating manifest file for efootball 23

@Real-n3tron Please read the error message: "out of memory". This happens when you don't specify a manifest file as an argument.
You wrote "outputManifest" as the third argument, but it should point to a file location, e.g. C:\Users\xxxxx\Desktop\manifest.json.

**Comment by CadiLillian** [comment]
image

I am getting this error with eFootball (UE 4.26.2) .ucas and .utoc files using the manifest function of the main.exe.
The lines that cause the error are

[Line 90](https://github.com/190nm/UEcastoc/blob/9e0936a3d26f364b5928d333ac22265ac24f34b5/manifest.go#L90) in manifest.go: 
```go
x, err := ParseDependencies(*data)
``` 
[Line 118](https://github.com/190nm/UEcastoc/blob/9e0936a3d26f364b5928d333ac22265ac24f34b5/manifest.go#L118) in manifest.go: 
```go
fd.Dependencies = append(fd.Dependencies, s.Deps[idx+uint32(j)])
``` 
[Line 239](https://github.com/190nm/UEcastoc/blob/9e0936a3d26f364b5928d333ac22265ac24f34b5/manifest.go#L239) in manifest.go:
```go
return s.extractDependencies(), nil
``` 
[Line 137](https://github.com/190nm/UEcastoc/blob/9e0936a3d26f364b5928d333ac22265ac24f34b5/dllAPI.go#L137) in dllAPI.go:
```go
manifest, err := d.constructManifest(ucasFname)
```

**Comment by Real-n3tron** [comment]
> > Getting fatal error while creating manifest file for efootball 23
> 
> @Real-n3tron Please read the error message: "out of memory". This happens when you don't specify a manifest file as an argument.
> You wrote "outputManifest" as the third argument, but it should point to a file location, e.g. C:\Users\xxxxx\Desktop\manifest.json.

@CadiLillian it's still not working

**Comment by mike9k1** [comment]
Hi @190nm and @gitMenv ! First off, I want to thank both of you for your incredible work on this tool. This looks like perhaps the best one out there for working with IOStore files.

For Dragon Quest X Offline (Unreal Engine 4.27):

We've been able to successfully use @190nm's fork to create a manifest for pakchunk1, pakchunk5, and pakchunk10. However, we seem to have an issue where the application will just hang forever (no error output) on pakchunk0's ucas and utoc. 

We're not sure if it's just too large or what the issue might be, but this may be the best forum to forward it.

Here's a link to the files: https://www.mediafire.com/folder/qbdourzg65ba7/DQX+Offline+iostore

And the AES key is: 0x8B51D59ED5C495E1ECF7E2960F218F4868A31CEF3DBC5248F70CADCF809D1193

I've sent @gitMenv a small donation as a token of appreciation for all that they've done so far. @190nm -- if you happen to have a Paypal or something of the sort, I'd be happy to send you one as well. (To be clear: nothing is expected in return, we just appreciate all that's been done so far, and i'm sure a number of other communities are just as grateful as we are!)

**Comment by chorimdeon** [comment]
Getting fatal error while trying to unpack utoc/ucas files ;;
image

**Comment by gitMenv** [comment]
@mike9k1 Thank you so much! I have been busy with other things lately, but I'm now at a point where I can get back into this project. The last thing I was working on, was getting rid of the manifest stuff altogether. There are still some mysteries left, and I hope that I can ultimately solve them. Then, the manifest files may not need to be generated at all. I'm glad that a fork was created in my absence that took this project a bit further, so thanks @190nm :D

**Review by gitMenv — APPROVED** [review]

**Comment by mike9k1** [comment]
I see that the pull request was merged (congrats 190nm!), but I also wanted to follow up here:

We ended up finding some success in creating mods, even though we weren't able to create a manifest for the largest pakchunk (and I think I know why now, but more on that in a bit). 

Thanks in part to @narknon, who gave us a tip: we could create the assets we want in Unreal Editor 4.27 using the correct pathing and allow it to generate a .ucas and .utoc. This .ucas/.utoc won't load into the game, BUT we can THEN use UECasToc to generate a manifest using that, unpack and then repack with UECasToc. This final .ucas/.utoc pair DOES load into the game. 

I'll link the full guide we created from this process (from our modding community's discord): https://discord.com/channels/499582383067234305/1024403618784362506/1139368073980280952

-------------------------

Today, I encountered something interesting... I have a file i'm looking to replace that's in Japanese: ひらがな.uasset

I follow the same guide, but strangely...I found that Unreal Editor will NOT assign it to any chunk ID other than 0 (I tried a handful of different methods). 

On top of that, as soon as the file is packed into pakchunk0, suddenly I'm now able to replicate the same issue that occurred with the base game's pakchunk0 -- it will eat memory like crazy (I had it clocking at over 10GB of RAM) and then either hang forever or crash due to running out of memory to allocate.

image

(This only occurs if the Japanese-named file is present in the .ucas/.utoc generated by Unreal Editor)

Is it possible that an asset named with non-alphanumeric characters causes this behavior?

Thanks again, and i'll follow up if I find out more.

**Comment by RenegadeWraith** [comment]
@mike9k1 Do you have a copy of that guide somewhere? The Discord link is broken.

**Comment by mike9k1** [comment]
I think it should still work AFAIK, but I forgot you’ll probably need the invite link for the server — https://discord.gg/ntf2vW4

Once you’re in, the link should take you to the relevant posts. 

To follow up on the issue raised above — this happened to be because UECasToc isn’t able to handle asset names that use WChar / WString. 

This was eventually resolved with UnrealUnZen some time later (which looks like it’s recently been renamed to UnrealReZen). So I think moving forward, I would probably recommend just generating a manifest & repacking using that if you can.

Nevertheless, we still have a good bit of our own ioStore documentation so feel free to dig through it or @ me there if you need some help/clarification on a specific issue.

**Comment by RenegadeWraith** [comment]
So from my understanding, the issue is that UnrealEngine forces the folder path to be `<project name>/Content/...` whereas you needed it to be `Game/...` 
UEcastoc is basically packing the same files, just with different pathing.

**Pull request merged**
